name: .NET Core MVC w Azure SQL in docker for contosobikes

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  AZURE_WEBAPP_NAME: contosobikessql

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-rc.1.20452.10
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Docker Build 
      run: |
        docker build . -t contosobikes/aspmvc:1.0.0
    - name: Docker login to ACR
      env:
        DOCKER_USER: ${{ secrets.ACR_USER }}
        DOCKER_PASSWORD: ${{ secrets.ACR_PASSWORD }}  
      run: |
         docker login consotobikes.azurecr.io -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Docker push
      run: |
        docker push contosobikes/aspmvc:1.0.0
        
    
